[project]
name = "agent-project"
version = "0.1.0"
description = "Base agent project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # ==== Base ====
    ## utils
    "notebook",
    "ipywidgets",
    ## log
    "loguru",
    ## path
    "pathlib",
    "omegaconf",
    ## tests
    "pytest",
    "pytest-asyncio",  # if only asyncio instead of anyio
]


[dependency-groups]
langgraph = [

]


[tool.uv]
#default-groups = [""]


[tool.pytest.ini_options]
asyncio_mode = "auto"

