[project]
name = "dl-project"
version = "0.1.0"
description = "UV projects configuration file template."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    ## utils
    "notebook",
    "ipywidgets",
    ## log
    "loguru",
    ## path
    "pathlib",
    "omegaconf",
    # main
    ## torch
    "torch",
#    "torchvision",
#    "torchaudio",
    ## lightning
    "lightning",
    "torchmetrics",
    ## logger
    "wandb",
    "tensorboard",
    ## config
    "hydra-core",
]

[dependency-groups]
dev = [
    # tests
    "pytest",
]

[tool.uv]
#default-groups = [""]

