[project]
name = "dl-project"
version = "0.1.0"
description = "Base deep learning project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # ==== Base ====
    ## utils
    "notebook",
    "ipywidgets",
    ## log
    "loguru",
    ## path
    "pathlib",
    "omegaconf",

    # ==== main ====
    ## ==== torch related ====
    "torch",
#    "torchvision",
#    "torchaudio",

    ## ==== logger ====
    "wandb",
    "tensorboard",
    ## ==== config ====
    "hydra-core",
]


[dependency-groups]
# data processing
data = [
    # structured data
    "polars",
#    "pandas",
    # stream data
    "jsonlines",
    # compatibility
    ## json related
    "orjson",
    "ujson",
    ## xlsx
#    "openyxl",
]
# training models
training = [
    # ==== nlp ====
#    "sentencepiece",

    # ==== cv ====
#    "opencv-python",
#    "moviepy",

    # audio
#    "soundfile",
]
# lightning related
lightning = [
    # ==== main ====
    ## ==== lightning ====
    "lightning",
    "torchmetrics",
]
# transformers related
transformers = [
    # ==== main ====
    ## ==== transformers ====
    ### base
    "transformers",
#    "sentence-transformers",
    ### dataset
    "datasets",
    ### training
    "accelerate",
    "trl",
    "peft",
    ### evaluation
    "lighteval",
    ## ==== integration tools ====
    "unsloth",
]
# Development
dev = [
    # ==== Linting and Formatting ====
    "ruff",
#    "mypy",
#    "pyright",
    # ==== Debugging and Dev Productivity ====
#    "ipython",
#    "pre-commit",
]
# Tests
test = [
    # pytest
    "pytest",
    "pytest-asyncio",  # if only asyncio instead of anyio
]
# Documents
docs = [
    # Sphinx
#    "sphinx",
#    "sphinx-rtd-theme",
#    "myst-parser",
    # MkDocs
#    "mkdocs",
#    "mkdocs-material",
#    "mkdocstrings",
]


[tool.uv]
default-groups = ["dev", "test", ]


[tool.ruff]
select = ["E", "F", ]
ignore = [
    "F401",
]
format.quote-style = "preserve"


[tool.pytest.ini_options]
asyncio_mode = "auto"

